name: Docker CI

on:
  workflow_call:
    inputs:
      image-name:
        description: 'A Docker image name passed from the caller workflow.'
        required: true
        type: string
      path:
        description: 'A path containing a Dockerfile passed from the caller workflow.'
        required: true
        type: string
      chaincode-label:
        description: 'An optional chaincode label passed from the caller workflow. If present, will prepare a chaincode package.'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_digest: ${{ steps.push.outputs.digest }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.image-name }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,format=long
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.path }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
