name: fabric-deployer Image CI

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'pakages/fabric-deployer/**'

jobs:
  docker_build:
    name: Docker build
    uses: ./.github/workflows/docker-build.yml
    with:
      image-name: ghcr.io/${{ github.repository }}/fabric-deployer
      path: pakages/fabric-deployer
