name: grpc-web Image CI

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'docker/grpc-web/**'

jobs:
  docker_build:
    name: Docker build
    uses: ./.github/workflows/docker-build.yml
    with:
      image-name: ghcr.io/${{ github.repository }}/grpc-web
      path: docker/grpc-web
