name: fabric-console Image CI

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'docker/console/**'

jobs:
  docker_build:
    name: Docker build
    uses: ./.github/workflows/docker-build.yml
    with:
      image-name: ghcr.io/${{ github.repository }}/fabric-console
      path: docker/console
